version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    container_name: dogs-postgres
    environment:
      POSTGRES_USER: dogs
      POSTGRES_PASSWORD: dogs
      POSTGRES_DB: db-dos-dogs
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    container_name: dogs-adminer
    ports:
      - 8080:8080

volumes:
  pgdata:
    driver: local